export enum ActionTypePlacesList {
  PLACES_LIST_REQUEST = "PLACES_LIST_REQUEST",
  PLACES_LIST_SUCCESS = "PLACES_LIST_SUCCESS",
  PLACES_LIST_FAIL = "PLACES_LIST_FAIL",

  PLACES_LIST_FILTER_REQUEST = "PLACES_LIST_FILTER_REQUEST",
  PLACES_LIST_FILTER_SUCCESS = "PLACES_LIST_FILTER_SUCCESS",
  PLACES_LIST_FILTER_FAIL = "PLACES_LIST_FILTER_FAIL",
}
