export enum ActionTypePlaceReviewPhoto {
    PLACE_REVIEW_PHOTO_SUCCESS = "PLACE_REVIEW_PHOTO_SUCCESS",
    PLACE_REVIEW_PHOTO_NULL = "PLACE_REVIEW_PHOTO_NULL",
    PLACE_REVIEW_PHOTO_REQUEST ="PLACE_REVIEW_PHOTO_REQUEST"
}