export enum ActionTypePlaceSelected {
  PLACE_SELECTED_REQUEST = "PLACE_SELECTED_REQUEST",
  PLACE_SELECTED_SUCCESS = "PLACE_SELECTED_SUCCESS",
  PLACE_SELECTED_FAIL = "PLACE_SELECTED_FAIL",
  PLACE_SELECTED_CHANGED = "PLACE_SELECTED_CHANGED",
  PLACE_SELECTED_NULL = "PLACE_SELECTED_NULL",
}
