name: Deploy code using yarn

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Yarn Setup
      # You may pin to the exact commit or the version.
      # uses: DerYeger/yarn-setup-action@f55be5383ea94f5eb25b20aee609af4603a68dde
      uses: DerYeger/yarn-setup-action@v1.0.1
      with:
        # The version of Node.js that will be used
        node-version: 14.x

    - name: Build
      run: |
        yarn install
        yarn build
    
    - name: Deploy to Google App Engine
      uses: google-github-actions/deploy-appengine@v0.4.0
      with:
       project_id: lhm-14-dps
       # working_directory: optional
       # deliverables: # optional
       credentials: ${{ secrets.gcp_credentials }}
